Develop
anatolykalugin/java-explore-with-me pull request #2
Opened 2022-11-29 19:03 UTC by anatolykalugin

2022-12-02 07:46 UTC, krylov-sergey-sergeevich requested changes
Привет, работа хорошая, давай немного поработаем и улучшим ее и будет зачет

1) Требуется везде добавить логирование в методах контроллеров
2) Кастомизировать исключения так чтобы для частоиспользумых сочетаний были заранее созданые классы например: CategoryAlreadyExistsException()
3) Избавиться от дублирования кода, в больших проектах это небезопасно

- **Доп по желанию:** почитай про swagger это полезная штука для оформления контроллеров
- **Доп по желанию:** почитай про Mapstruct, сейчас тут его применять излишне

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on README.md
> +# ExploreWithMe
ReadMe давай оформим получше: **"Добавим блоки"**

1) Используемые технологии
2) Краткое описание сервисов
3) Команды описаны для старта докера

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on ewm/pom.xml
> +            <version>2.7.1</version>
Зачем тут версия если мы используем parent spring boot?

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on ewm/pom.xml
> +            <version>2.7.1</version>
Зачем тут версия если мы используем parent spring boot?

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on ewm/pom.xml
> +    <properties>
Блок с проперти должны быть выше dependency блока

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/ewm/category/dto/CategoryMapper.java
> +public class CategoryMapper {
Рекомендую почитать на будущее про Mapstruct, сейчас тут его применять излишне

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +public class CategoryServiceImpl implements CategoryService {
В классе есть дубли проверок, давай их вынесем в методы

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/ewm/event/dto/EventCutDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Данный паттерн можно вынести в переменную класса Constants и везде использовать

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +public class EventServiceImpl implements EventService {
Есть дублирующие участки кода

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/ewm/stclient/WebClientConfiguration.java
> +public class WebClientConfiguration {
Впервые вижу что студент применяем WebClient в дипломном проекте 👍🏻

2022-12-02 07:46 UTC, krylov-sergey-sergeevich commented on stats/pom.xml
> +    <properties>
Проперти сверху на зависимостями должны быть

2022-12-02 08:50 UTC, anatolykalugin commented on ewm/pom.xml
> +    <properties>
Исправлено

2022-12-02 09:48 UTC, anatolykalugin commented on ewm/src/main/java/ru/practicum/ewm/event/dto/EventCutDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Готово

2022-12-02 09:53 UTC, anatolykalugin commented on ewm/src/main/java/ru/practicum/ewm/category/dto/CategoryMapper.java
> +public class CategoryMapper {
Прочитал и принял к сведению, спасибо!

2022-12-02 09:56 UTC, anatolykalugin commented on ewm/pom.xml
> +            <version>2.7.1</version>
Исправлено

2022-12-02 09:56 UTC, anatolykalugin commented on ewm/pom.xml
> +            <version>2.7.1</version>
Исправлено

2022-12-02 10:18 UTC, anatolykalugin commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +public class EventServiceImpl implements EventService {
Исправлено

2022-12-02 11:10 UTC, anatolykalugin commented on README.md
> +# ExploreWithMe
Ридми дополнен

2022-12-02 11:13 UTC, anatolykalugin commented
Все правки в соответствии с комментариями после ревью внесены, про mapstruct и swagger прочитал.
Большое спасибо за замечания с пояснениями и за советы!

2022-12-03 10:42 UTC, krylov-sergey-sergeevich requested changes
Привет, хорошая работа - зачет!

Что потенциально можно улучшать:
- Докинуть где надо @UtillityClass lombok 
-  **Учесть и поправить нейминг методов:** get - это или получение объекта или исключение, find - это или объект или null
- @JsonFormat - не везде где можно применен к датам
- Подход с исключениями хорош, но можно лучше. Исключения если присмотреться похожи по структуре, не хочется ли создать структуру исключений или побольше кастомных исключений и не писать каждый раз весь текст причины исключения, а чисто название например NotFoundCategoryException extend NotFoundException это не обязательно, но как на подумать. Плюс в некоторых исключениях не пишутся id объектов которые не могут найти или с которыми проблема.

2022-12-03 10:42 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/ewm/exception/Handler.java
> +public class Handler {
Попробуй поизучать как можно сделать так чтобы еще возвращать в сообщение с ошибкой request path по которому был сделан запрос. Один из вариантов это воспользоваться: **HttpServletRequest**

2022-12-03 10:43 UTC, krylov-sergey-sergeevich approved these changes

2022-12-03 10:43 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    @ManyToMany(cascade = CascadeType.PERSIST, fetch = FetchType.LAZY)
Не туда нажал в прошлый раз, зачет

p,s Хорошо что Lazy применено и каскад не all

2022-12-03 10:44 UTC, krylov-sergey-sergeevich commented
Ну и докину: избавляться от дублирования кода можно много где еще для нахождения таких мест рекомендую самому смотреть pr сверху вниз, а не через IDEA

2022-12-04 09:02 UTC, merged